_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("xview_instance_segmentation_dataset_train",)
  TEST: ("xview_instance_segmentation_dataset_val",)
DATALOADER:
  NUM_WORKERS: 2
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 1
  BASE_LR: 0.0005
TEST:
  EVAL_PERIOD: 1000